version: '3'

silent: true

vars:
  BROWSER: '{{.BROWSER | default "open"}}'
  MUTATE_PATH: '{{.MUTATE_PATH | default "instant_python"}}'

includes:
  dev:
    taskfile: task/dev.yml
    aliases: [development]

  test:
    taskfile: task/test.yml
    aliases: [tests]

  deps:
    taskfile: task/deps.yml
    aliases: [dep]

  docs:
    taskfile: task/docs.yml
    aliases: [doc]


tasks:
  # ── Default ──────────────────────────────────────────────────────────────────
  default:
    desc: Show this help.
    cmds:
      - task --list-all

  help:
    desc: Show this help
    cmds:
      - task --list

  # ── Code Quality ─────────────────────────────────────────────────────────────
  type-check:
    desc: Run mypy type checking
    cmds:
      - printf "\n⌛ Running type checking with mypy...\n"
      - uv run mypy

  lint:
    desc: Apply ruff linting fix
    cmds:
      - printf "\n⌛ Applying linting fixes...\n"
      - uvx ruff check --fix instant_python test

  format:
    desc: Apply ruff format fix
    cmds:
      - printf "\n⌛ Formatting project code...\n"
      - uvx ruff format instant_python test
  watch:
    desc: Run all test with every change.
    cmds:
      - uv run ptw --runner "pytest -n auto test -ra"

  # ── Security ─────────────────────────────────────────────────────────────────
  audit:
    desc: It audits dependencies and source code
    cmds:
      - printf "\n⌛ Running security audit...\n\n"
      - uv run -m pip_audit --progress-spinner off --ignore-vuln GHSA-4xh5-x5gv-qwph

  secrets:
    desc: It checks for secrets in the source code
    cmds:
      - printf "\n⌛ Checking secrets...\n\n"
      - uv run -m pre_commit run gitleaks --all-files
