name: Release and Publish

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  release:
    if: "!startsWith(github.event.head_commit.message, 'bump:')"
    runs-on: ubuntu-latest
    permissions:
      contents: write
    outputs:
      released: ${{ steps.released.outputs.released }}
      tag: ${{ steps.released.outputs.tag }}

    steps:
      - name: 🛡️ Harden runner
        uses: step-security/harden-runner@bf7454d06d71f1098171f2acdf0cd4708d7b5920 # v2.20.0
        with:
          egress-policy: audit

      - name: 📥 Checkout the repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0  # v7.0.0
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: 🔖 Create release
        id: released
        uses: python-semantic-release/python-semantic-release@350c48fcb3ffcdfd2e0a235206bc2ecea6b69df0 # v10.0.2
        with:
          build: true
          push: true
          changelog: true
          commit: true
          tag: true
          vcs_release: true
          config_file: pyproject.toml
          github_token: ${{ secrets.GITHUB_TOKEN }}
          git_committer_email: ${{ vars.GIT_COMMITTER_EMAIL }}
          git_committer_name: ${{ vars.GIT_COMMITTER_NAME }}
          ssh_public_signing_key: ${{ vars.SSH_PUBLIC_SIGNING_KEY }}
          ssh_private_signing_key: ${{ secrets.SSH_PRIVATE_SIGNING_KEY }}

  build-and-publish:
    name: Publish to PyPI
    needs:
      - release
    if: needs.release.outputs.released == 'true' || github.event_name == 'release'
    runs-on: ubuntu-latest
    environment: release
    permissions:
      id-token: write

    steps:
      - name: 🛡️ Harden runner
        uses: step-security/harden-runner@bf7454d06d71f1098171f2acdf0cd4708d7b5920 # v2.20.0
        with:
          egress-policy: audit

      - name: 📥 Checkout the repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0  # v7.0.0
        with:
          fetch-depth: 0
          persist-credentials: false
          ref: refs/tags/${{ needs.release.outputs.tag }}

      - name: 🛠️ Setup environment
        uses: ./.github/actions/python_setup

      - name: 🏃 Build package
        run: uv build

      - name: 🚀 Publish
        uses: pypa/gh-action-pypi-publish@release/v1
